#pragma once

#define MIDI_ADVANCED

#define SPLIT_HAND_PIN B14
#define MASTER_LEFT

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_OLED_ENABLE

#define OLED_TIMEOUT 10000

#define VENDOR_ID       0xFEEE
#define PRODUCT_ID      0x7075
#define DEVICE_VER      0x0001
#define MANUFACTURER    IFKB
#define PRODUCT         sofle

/* key matrix size */
// Rows are doubled-up
#define MATRIX_ROWS 10
#define MATRIX_COLS 6

// wiring of each half
#define MATRIX_ROW_PINS { B3, B4, B5, A2, A3 }
#define MATRIX_COL_PINS { A1, A7, A6, A5, B0, B1 }
#define MATRIX_ROW_PINS_RIGHT { B3, B4, B5, A2, A3 }
#define MATRIX_COL_PINS_RIGHT { A1, A7, A6, A5, B0, B1 }
#define DIODE_DIRECTION COL2ROW

#define TAPPING_TERM 250
#define DEBOUNCE 5

//整体开关
#define RGB_MOS B8
//底灯开关
#define RGB_LOW_MOS B9

#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_SLEEP

/* encoder support */
#define ENCODERS_PAD_A { B11 }
#define ENCODERS_PAD_B { B10 }
#define ENCODERS_PAD_A_RIGHT { B11 }
#define ENCODERS_PAD_B_RIGHT { B10 }
// #define ENCODER_DEFAULT_POS 0x3
// #define ENCODER_RESOLUTION 2
#define ENCODER_RESOLUTION 4

#define SERIAL_USART_FULL_DUPLEX   // Enable full duplex operation mode.
#define SERIAL_USART_TX_PIN A9     // USART TX pin
#define SERIAL_USART_RX_PIN A10     // USART RX pin

#define DYNAMIC_KEYMAP_LAYER_COUNT 15

// #define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 10239
// #define EEPROM_SIZE 10239

// // //STM32F103xB
// #define FEE_PAGE_SIZE 0x400 // Page size = 1KByte
// #define FEE_PAGE_COUNT 20

// \vial-qmk\quantum\quantum.c
#define NO_SUSPEND_POWER_DOWN ture
#define RGB_DISABLE_WHEN_USB_SUSPENDED

//tim1ch3n
#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_COMPLEMENTARY_OUTPUT ture
#define WS2812_DMA_STREAM STM32_DMA1_STREAM5

#define RGB_DI_PIN B15
#define RGBLED_NUM 82
#define DRIVER_LED_TOTAL 82
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
#define RGB_MATRIX_SPLIT { 41, 41 }
#define SPLIT_TRANSPORT_MIRROR
#define RGB_MATRIX_LED_FLUSH_LIMIT 32

#define RGBLIGHT_ANIMATIONS
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

// RGB Matrix Animation modes. Explicitly enabled
// For full list of effects, see:
// https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
// #define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
// #define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
// #define ENABLE_RGB_MATRIX_BAND_SAT
// #define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
// #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
// #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
// #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
// #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
// #define ENABLE_RGB_MATRIX_DUAL_BEACON
// #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
// #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
// #define ENABLE_RGB_MATRIX_RAINDROPS
// #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
// #define ENABLE_RGB_MATRIX_HUE_PENDULUM
// #define ENABLE_RGB_MATRIX_HUE_WAVE
// #define ENABLE_RGB_MATRIX_PIXEL_RAIN
// #define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
// enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP1
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
// #define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

// #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 128
