# MCU name
MCU = STM32F103
BOOTLOADER = tinyuf2
ifeq ($(strip $(BOOTLOADER)), tinyuf2)
	MCU_LDSCRIPT = STM32F103xB_uf2
	FIRMWARE_FORMAT = uf2
	BOARD = STM32_F103_STM32DUINO
	MCU_STARTUP ?= stm32f1xx
endif
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
OPT_DEFS += -DBOOTLOADER_TINYUF2
OPT_DEFS += -DRIGHTCAT

BOOTMAGIC_ENABLE = yes	# Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes	# Mouse keys
EXTRAKEY_ENABLE = yes	# Audio control and System control
NKRO_ENABLE = yes
MIDI_ENABLE = yes

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart

ENCODER_ENABLE = yes

OLED_ENABLE = no
OLED_DRIVER = SSD1306

SWAP_HANDS_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = pwm

WPM_ENABLE = yes

